### PR TITLE
WIP: UPG: InfrastructureModels v0.6, PowerModelsDistribution v0.11, PowerModels v0.18

### PR DESCRIPTION
**Pull request by pseudocubic**
This is a draft of the refactor to upgrade to the latest versions of PowerModels and PowerModelsDistribution, which include the multi-infrastructure capabilities.

This refactor is fairly drastic, particularly on the Distribution-side, but the changes to the unit tests were all in solution output format and function calls, not in the values of the solutions.

- Added support for InfrastructureModels v0.6.0, which added support for multi-infrastructure modeling
- Added support for PowerModelsDistribution v0.11.2, which added support for multi-infrastructure modeling, and removed all PowerModels dependencies
- Added support for PowerModels v0.18, which added support for multi-infrastructure modeling
- Refactored "fault" data model to be consistent across data models
- Refactored fault study solvers to separate variable creation from constraints
- Removed support for JuMP versions < v0.21
- Updated documentation, and added tutorials in `examples`, which adds Pluto and Gumbo dependencies to the documentation builds
- Refactored all functions related to Distribution data models so that the ENGINEERING data model is used by default
- Removed dependencies on Memento, JSON (this was unused in current code-base)

Tutorials on usage for both transmission and distribution data sets with fault studies can be found in `examples`, and the documentation when it is built.

## TODO

- [x] changelog
- [x] documentation
- [x] finalize ENG model data structure
- [x] add sequence fault currents as JuMP Expressions to the model

### CODE REVIEW

**Comment by akbarnes** [comment]
Both the fault and results data structures look good, which was my main concern. There was an error in the "zero_sequence_current" results field, I've fixed this (see commit 51fd744d4de68c0bd2e13f747836c414da5f0520 for more information). Also could not resist the urge to change naming a bit, and filled in the quickstart.

A naming convention question, would it make more sense to use `add_mc_fault` for the distribution case - I think that this is a different function?

**Review by bluejuniper — APPROVED** [review]
Looks good, made a couple changes regarding sequence currents and some naming conventions - see my earlier comment.

**Comment by bluejuniper** [comment]
Talked to @jtabarez, 

1. We would like to use expressions for the sequence quantities rather than calculating ad-hoc in solution.jl
2. Sequence quantities need to be expressed as separate real and imaginary values in the result as complex values won't survive json serialization.

**Comment by pseudocubic** [comment]
I made some minor updates, the biggest of which is changing "fault_current" in `solution_fs!` to `cf`, `cf_fr`, `cf_to`, or `cf_bus`, as appropriate. 

If you are okay with those changes (and unit tests still pass), i think we are ready to merge / tag

**Review by jtabarez — APPROVED** [review]

**Pull request merged**
